version: '3'

services:
  web:
    build: .
    container_name: django_web
    ports:
      - "8000:8000"  # Si vous souhaitez tester en local via gunicorn, sinon Apache sur 80
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DATABASE_URL=mysql://root:rootpassword@db:3306/fraud_db
      - DB_NAME=fraud_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306

  db:
    image: mariadb:10.6
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fraud_db
    ports:
      - "3306:3306"  # Accès à la base de données depuis l'extérieur si nécessaire (par exemple pour MySQL Workbench)
