# Generated by Django 5.2 on 2025-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('montant', models.FloatField()),
                ('type_transaction', models.CharField(max_length=50)),
                ('is_fraudulent', models.BooleanField(default=False)),
            ],
        ),
    ]
